import {
    MdOutlineMailOutline,
    MdOutlineDashboard,
    MdOutlineAttachMoney,
    MdOutlineCircle,
    MdLogout,
    MdOutlinePhoneInTalk,
    MdPeopleOutline,
    MdOutlineGroups3,
    MdOutlineLeaderboard,
    MdOutlineGeneratingTokens,
    MdAssignmentAdd,
    MdStarBorderPurple500,
    MdArrowRight,
    MdDoorbell,
    MdOutlineCategory,
    MdOutlineEditNote,
    MdOutlineAddTask,
    MdOutlinePassword,
    MdTimer10,
    MdTimer3,
    MdMobileFriendly,
    MdOutlineAddchart,
    MdOutlineAddChart,
} from "react-icons/md";
import {
    PiUsers,
    PiKeyLight,
    PiSun,
    PiMoon,
    PiMoney,
    PiCurrencyDollarSimple,
    PiHandDeposit,
    PiBellSimple,
    PiNotePencil,
    PiArrowsLeftRightFill,
    PiUserFocus,
    PiCalendarLight,
    PiGlobe,
    PiPackageLight,
    PiBuildingsBold,
    PiUsersThree,
    PiUsersFour,
    PiPrinter,
    PiEyeBold,
    PiClockUserFill,
    PiUserCircleGear,
    PiPlusCircleFill,
    PiUserCircleFill,
    PiBell,
    PiPlusCircle,
    PiMoonLight,
    PiMoonThin,
    PiMoonStarsThin,
    PiPercent,
    PiPercentBold,
    PiCurrencyDollar,
    PiEyeSlashBold,
    PiIdentificationCard,
    PiStarFour,
    PiStarFourThin,
    PiBomb,
} from "react-icons/pi";
import {
    GrTransaction,
    GrHomeRounded,
    GrSearch,
    GrFilter,
    GrMenu,
    GrPowerReset,
    GrUserFemale,
    GrUserManager,
    GrSteps,
    GrUserPolice,
    GrTools,
    GrUserSettings,
    GrLink,
    GrMapLocation,
    GrLineChart,
    GrHistory,
} from "react-icons/gr";
import {
    BsBell,
    BsBuildings,
    BsExclamationTriangle,
    BsFilePdf,
    BsHeartPulse,
    BsTelephone,
    BsTelephoneInbound,
    BsTelephoneOutbound,
    BsTools,
    BsTrash3,
    BsFiletypeXlsx,
    BsFiletypeDocx,
    BsFiletypePpt,
    BsFiletypePptx,
    BsClipboardCheck,
    BsClipboardCheckFill,
    BsCheckCircleFill,
    BsStars,
} from "react-icons/bs";
import {
    TbDatabaseCog,
    TbDotsVertical,
    TbGripVertical,
    TbLockPassword,
    TbPackages,
    TbRefresh,
    TbUserCheck,
    TbUserPlus,
    TbUserQuestion,
    TbWorldWww,
    TbTrashOff,
    TbMessages,
    TbInfoHexagon,
    TbProgressHelp,
    TbHomeLink,
    TbTableImport,
    TbTableExport,
    TbBuildingPavilion,
    TbPasswordUser,
    TbUsersGroup,
    TbPoint,
    TbPointFilled,
} from "react-icons/tb";
import {
    IoInfiniteOutline,
    IoLockClosedOutline,
    IoSettingsOutline,
    IoDownloadOutline,
    IoKeyOutline,
    IoCheckmarkDoneOutline,
    IoHeartDislikeOutline,
    IoKeypad,
    IoIdCardOutline,
    IoDocumentTextOutline,
} from "react-icons/io5";
import {
    FcBusinesswoman,
    FcManager,
    FcTouchscreenSmartphone,
    FcDepartment,
    FcCurrencyExchange,
    FcGoogle,
} from "react-icons/fc";
import {
    IoIosPeople,
    IoIosNotifications,
    IoLogoYoutube,
    IoMdTimer,
    IoMdCheckmarkCircleOutline,
    IoIosCheckmarkCircleOutline,
    IoMdCheckmark,
    IoMdHeartEmpty,
    IoMdHeartHalf,
    IoMdHeart,
    IoMdClose,
    IoMdCloseCircleOutline,
    IoMdInformationCircleOutline,
    IoMdAdd,
    IoMdAttach,
} from "react-icons/io";
import {
    FiAlertTriangle,
    FiPackage,
    FiPhoneOutgoing,
    FiShield,
    FiUser,
} from "react-icons/fi";
import {
    LiaBarsSolid,
    LiaIndustrySolid,
    LiaProductHunt,
    LiaTagsSolid,
    LiaTagSolid,
    LiaUserGraduateSolid,
    LiaIdCard,
    LiaChevronLeftSolid,
    LiaChevronRightSolid,
    LiaCalendarCheckSolid,
} from "react-icons/lia";
import {
    FaExpeditedssl,
    FaTasks,
    FaFacebook,
    FaWhatsapp,
    FaLinkedinIn,
    FaStar,
    FaInfo,
    FaArrowUp,
    FaArrowDown,
    FaLink,
    FaRegAddressCard,
    FaRegFlag,
    FaUnlink,
    FaStarOfLife,
    FaTwitter,
    FaLinkedin,
} from "react-icons/fa";
import { CiLink, CiViewList, CiVideoOn } from "react-icons/ci";
import { SiStatuspal, SiCrowdsource } from "react-icons/si";
import {
    GiArrowScope,
    GiArtificialIntelligence,
    GiBullseye,
    GiChart,
    GiKeyLock,
    GiKeyring,
    GiModernCity,
    GiProgression,
    GiReceiveMoney,
    GiRingingBell,
    GiSmartphone,
    GiThreeKeys,
    GiWarlockEye,
} from "react-icons/gi";
import {
    RiCodeAiLine,
    RiCodeFill,
    RiCodeSSlashFill,
    RiContactsBook3Line,
    RiFolderUploadLine,
    RiUpload2Fill,
    RiUserCommunityLine,
} from "react-icons/ri";
import { HiLink } from "react-icons/hi";
import { TiArrowLeftOutline, TiSocialDribbbleCircular } from "react-icons/ti";
import {
    BiMaleFemale,
    BiSolidInstitution,
    BiSolidReport,
} from "react-icons/bi";
import {
    LuBrain,
    LuBrainCircuit,
    LuCalendarCheck,
    LuCalendarClock,
    LuCalendarHeart,
    LuCalendarMinus,
    LuCalendarPlus,
    LuCalendarPlus2,
    LuChartNoAxesCombined,
    LuChartSpline,
    LuClipboardCheck,
    LuFolderSync,
    LuTypeOutline,
    LuWrench,
} from "react-icons/lu";
import { SlEnvelopeOpen, SlLike, SlScreenSmartphone } from "react-icons/sl";
import { RxActivityLog } from "react-icons/rx";
import { WiCloudRefresh } from "react-icons/wi";
import { AiOutlineAudio } from "react-icons/ai";
import {
    CgChevronDoubleLeft,
    CgChevronDoubleRight,
    CgChevronDown,
    CgChevronUp,
} from "react-icons/cg";
import { VscStarEmpty } from "react-icons/vsc";

const ICON_MAP = {
    audio: AiOutlineAudio,
    alert: FiAlertTriangle,
    attachment: IoMdAttach,
    ai: GiArtificialIntelligence,
    ai2: LuBrainCircuit,
    ai3: LuBrain,
    ai4: PiStarFourThin,
    aiStars: BsStars,
    arrowRight: MdArrowRight,
    arrowLeft: TiArrowLeftOutline,
    arrowDown: CgChevronDown,
    arrowUp: CgChevronUp,
    arrowChevronLeft: CgChevronDoubleLeft,
    arrowChevronRight: CgChevronDoubleRight,
    arrowChevronLeft2: LiaChevronLeftSolid,
    arrowChevronRight2: LiaChevronRightSolid,
    add: PiPlusCircle,
    addCircleFill: PiPlusCircleFill,
    addPlus: IoMdAdd,
    addChart: MdOutlineAddChart,
    assign: MdAssignmentAdd,
    activity: MdOutlineAddTask,
    bullet: TbPoint,
    bulletFilled: TbPointFilled,
    bell: PiBellSimple,
    bell2: BsBell,
    bars: LiaBarsSolid,
    bomb: PiBomb,
    circle: MdOutlineCircle,
    cross: IoMdClose,
    crossCircle: IoMdCloseCircleOutline,
    contact: LiaIdCard,
    contact2: FaRegAddressCard,
    contactMethod: PiClockUserFill,
    category: MdOutlineCategory,
    currencyDolor: PiCurrencyDollar,
    currencyExchange: FcCurrencyExchange,
    currencyType: GiReceiveMoney,
    company: TbBuildingPavilion,
    city: GiModernCity,
    country: FaRegFlag,
    code: RiCodeFill,
    code2: RiCodeSSlashFill,
    codeAi: RiCodeAiLine,
    dashboard: MdOutlineDashboard,
    dolor: PiCurrencyDollarSimple,
    deposit: PiHandDeposit,
    downArrow: FaArrowDown,
    doc: IoDocumentTextOutline,
    txt: IoDocumentTextOutline,
    docx: BsFiletypeDocx,
    delete: BsTrash3,
    designation: LiaUserGraduateSolid,
    date: PiCalendarLight,
    dateStart: LuCalendarPlus,
    dateEnd: LuCalendarMinus,
    dateReminder: LuCalendarHeart,
    dateCreated: LuCalendarCheck,
    dateUpdated: LuCalendarClock,
    database: TbDatabaseCog,
    department: FcDepartment,
    departments: BsBuildings,
    download: IoDownloadOutline,
    email: MdOutlineMailOutline,
    earning: MdOutlineAttachMoney,
    edit: PiNotePencil,
    exclamation: BsExclamationTriangle,
    export: TbTableExport,
    filter: GrFilter,
    female: GrUserFemale,
    fax: PiPrinter,
    facebook: FaFacebook,
    followup: FiPhoneOutgoing,
    followup2: SlEnvelopeOpen,
    groups: MdOutlineGroups3,
    globe: PiGlobe,
    goBack: TiArrowLeftOutline,
    googleColorful: FcGoogle,
    home: GrHomeRounded,
    hide: PiEyeSlashBold,
    heart: BsHeartPulse,
    history: GrHistory,
    product: LiaProductHunt,
    industry: LiaIndustrySolid,
    infinite: IoInfiniteOutline,
    info: IoMdInformationCircleOutline,
    info2: TbInfoHexagon,
    info3: FaInfo,
    import: TbTableImport,
    id: IoIdCardOutline,
    key: PiKeyLight,
    keys: GiThreeKeys,
    logout: MdLogout,
    lock: IoLockClosedOutline,
    lead: TbUsersGroup,
    lead2: PiUsersThree,
    list: CiViewList,
    link: HiLink,
    link2: FaLink,
    link3: GrLink,
    linkHome: TbHomeLink,
    love: IoMdHeartEmpty,
    loveHalf: IoMdHeartHalf,
    loveNot: IoHeartDislikeOutline,
    loveFill: IoMdHeart,
    linkedIn: FaLinkedin,
    moon: PiMoonStarsThin,
    money: PiMoney,
    time: IoMdTimer,
    menu: GrMenu,
    male: GrUserManager,
    man: FcManager,
    members: IoIosPeople,
    members2: MdPeopleOutline,
    modules: FiPackage,
    mobile: SlScreenSmartphone,
    mobile2: GiSmartphone,
    notification: IoIosNotifications,
    notificationFill: MdDoorbell,
    notificationRing: PiBell,
    notDelete: TbTrashOff,
    note: MdOutlineEditNote,
    nameFirst: TbUserPlus,
    nameLast: TbUserQuestion,
    nameNick: TbUserCheck,
    organization: PiBuildingsBold,
    ppt: BsFiletypePpt,
    pptx: BsFiletypePptx,
    opportunity: GiArrowScope,
    opportunity2: GiBullseye,
    profile: PiUserFocus,
    projects: LuClipboardCheck,
    projects2: BsClipboardCheckFill,
    projects3: FaExpeditedssl,
    projects4: BsClipboardCheck,
    percent: PiPercent,
    percentBold: PiPercentBold,
    permissions: IoKeyOutline,
    progress: GiProgression,
    progress2: TbProgressHelp,
    phone: MdOutlinePhoneInTalk,
    package: PiPackageLight,
    packages: TbPackages,
    password: TbLockPassword,
    priority: GiRingingBell,
    pdf: BsFilePdf,
    postalCode: GrMapLocation,
    reset: GrPowerReset,
    refresh: TbRefresh,
    refreshCloud: WiCloudRefresh,
    roles: FiShield,
    rating: MdOutlineGeneratingTokens,
    report: LuChartNoAxesCombined,
    report2: GrLineChart,
    report3: LuChartSpline,
    related: LuFolderSync,
    required: FaStarOfLife,
    required2: VscStarEmpty,
    save: RiUpload2Fill,
    save2: RiFolderUploadLine,
    social: TiSocialDribbbleCircular,
    sun: PiSun,
    salutation: BiMaleFemale,
    search: GrSearch,
    star: FaStar,
    setting: IoSettingsOutline,
    setting2: GrTools,
    setting3: LuWrench,
    settingUser: GrUserSettings,
    source: SiCrowdsource,
    stage: GrSteps,
    status: SiStatuspal,
    star: MdStarBorderPurple500,
    sms: TbMessages,
    success: IoMdCheckmarkCircleOutline,
    success2: IoIosCheckmarkCircleOutline,
    success3: IoCheckmarkDoneOutline,
    success4: IoMdCheckmark,
    successFill: BsCheckCircleFill,
    transaction: GrTransaction,
    tools: BsTools,
    telephone: BsTelephone,
    telephoneIn: BsTelephoneInbound,
    telephoneOut: BsTelephoneOutbound,
    transactions: PiArrowsLeftRightFill,
    tag: LiaTagSolid,
    tags: LiaTagsSolid,
    task: FaTasks,
    taskType: LuTypeOutline,
    twitter: FaTwitter,
    token: GiKeyring,
    unlink: FaUnlink,
    user: FiUser,
    users: PiUsers,
    users3: PiUsersThree,
    users4: PiUsersFour,
    usersAssociates: RiUserCommunityLine,
    usersOwner: GrUserPolice,
    userCircle: PiUserCircleGear,
    userCircleFill: PiUserCircleFill,
    upperArrow: FaArrowUp,
    woman: FcBusinesswoman,
    whatsapp: FaWhatsapp,
    website: TbWorldWww,
    xlsx: BsFiletypeXlsx,
    youtube: IoLogoYoutube,
    yes: SlLike,
    vertical: TbDotsVertical,
    verticalDouble: TbGripVertical,
    view: PiEyeBold,
    video: CiVideoOn,
    mp4: CiVideoOn,
};

export const getIcon = function (icon = "") {
    return ICON_MAP[icon] || ICON_MAP["user"];
};
