export const TenantDataEmpSizeCreateInputs = [
    {
        name: "name",
        type: "text",
        icon: "name",
        label: "Label",
        placeholder: "Enter employee size like (Size 00 to 100 )",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-name",
    },
    {
        name: "note",
        type: "text",
        icon: "name",
        label: "Note",
        placeholder: "",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-note",
    },
    {
        name: "size",
        type: "text",
        icon: "name",
        label: "Actual size",
        placeholder: "",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-size",
    },
];
