export const EmailSettingCreateInputs =  [
    {
        name: "host",
        type: "text",
        icon: "name",
        label: "Host",
        placeholder: "Enter the host",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-host",
    },
    {
        name: "port",
        type: "text",
        icon: "name",
        label: "Port",
        placeholder: "Enter the port",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-port",
    },
    {
        name: "password",
        type: "text",
        icon: "name",
        label: "Password",
        placeholder: "Enter the password",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-password",
    },
    {
        name: "encryption",
        type: "text",
        icon: "name",
        label: "Encryption",
        placeholder: "Enter the encryption",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-encryption",
    },
    {
        name: "userName",
        type: "text",
        icon: "name",
        label: "User name",
        placeholder: "Enter the user name",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-userName",
    },
    {
        name: "mailFromAddress",
        type: "text",
        icon: "name",
        label: "Mail from address",
        placeholder: "Enter mail from address",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-mail-from-address",
    },
  
];