export const TenantLeadStageCreateInputs =  [
    {
        name: "name",
        type: "text",
        icon: "name",
        label: "Name",
        placeholder: "Enter lead stage name",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-name",
    },
    {
        name: "label",
        type: "text",
        icon: "name",
        label: "Label",
        placeholder: "Enter lead stage label",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-label",
    },
    {
        name: "stage_percent",
        type: "number",
        icon: "name",
        label: "Stage percent",
        placeholder: "Enter lead stage percent",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-percent",
    },
    {
        name: "resolution_days",
        type: "number",
        icon: "name",
        label: "Resolution days",
        placeholder: "Enter resolution days",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-resolution-days",
    },
    {
        name: "resolution_hours",
        type: "number",
        icon: "name",
        label: "Resolution hours",
        placeholder: "Enter resolution hours",
        note: "exampleName",
        required: false,
        inForm: true,
        inPreview: true,
        gridSize: "",
        autoCompleteAttr: "new-resolution-hours",
    },
  
];